volumes:
  data:

services:
  postgres:
    container_name: book-postgres
    image: postgres:12
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: book_social
    ports:
      - 5434:5432